# Generated by Django 5.1.2 on 2024-10-28 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.itinerary')),
            ],
        ),
        migrations.AddField(
            model_name='itinerary',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.package'),
        ),
    ]
